#!/bin/bash
# Set API Key here
PUUSH_API_KEY=""

#put this file in /usr/local/bin

# Puush for linux
# Owner : Sunmock Yang (modified for shutter by Vikram Melkote)
# www.sunmock.com
# May 2014 (edited Jan 2018)
#
# Dependencies:
# - shutter
# - curl
# - zenity
# - xclip
# - notify-send
#
# Licence : Beerware
#
# Instructions:
# - Add your puush API key to PUUSH_API_KEY (You can find your API key at http://puush.me/account/settings)
# - Place this file wherever you want (/usr/local/bin)
# - Set up keyboard shortcuts within linux (in Ubuntu it's system settings > keyboard > keyboard shortcuts > custom shortcuts)
#
# 		command			description		(recommended keyboard shortcut)
#		---------------------------------------------------------------
#		puush -c		puush window	(Ctrl + Shift + 2/@)
#		puush -a		puush desktop	(Ctrl + Shift + 3/#)
#		puush -b		area puush		(Ctrl + Shift + 4/$)
#		puush -d		file upload		(Ctrl + Shift + U)
#		puush -e		puush clipboard	(Ctrl + Shift + 1/!)
#
#
# Notes:
# - Link(s) will be copied into clipboard and appear in notifications
# - puush curl upload code borrowed from online sources

# Usage: puushFile [fileName]
function puushFile ()
{
	if [ -z "$1" ]; then
		echo "No file specified"
		exit 1
	# elif [ ! -f "$1" ]; then
	# 	echo "Puush cancelled"
	# 	exit 1
	fi

	fileURL=`curl "https://puush.me/api/up" -# -F "k=$PUUSH_API_KEY" -F "z=waifu" -F "f=@$1" | sed -E 's/^.+,(.+),.+,.+$/\1\n/'`

	if [ ! -z "$fileURL" ]; then
		#Copy link to clipboard, show notification
		printf $fileURL | xclip -selection "clipboard"
		notify-send -i "$( cd "$( dirname "$0" )" && pwd )/icon.png" -t 2000 "puush complete!" "$fileURL"
	fi
}

function helpText ()
{
  printf "_____________ puush for linux _____________\n"
  printf "Created by Sunmock Yang using the puush api\n"
  printf "\n"
  printf "Usage:\n"
  printf "  puush [OPTIONS] [PATH]\n"
  printf "\n"
  printf "OPTIONS:\n"
  printf "  -a                 puush entire desktop\n"
  printf "  -b                 select area to puush\n"
  printf "  -c                 puush current window\n"
  printf "  -d                 puush specific file (opens file dialog)\n"
  printf "  -e                 puush clipboard contents\n"
  printf "\n"
  printf "  --help,-h          show this page\n"
  printf "\n"
  printf "PATH:\n"
  printf "  PATH               optional: path of file to puush\n"
}

function generateFileName () { echo "/home/dunixify/puush/Screenshot_Xubuntu_$(date +"%Y-%m-%d_%H-%M-%S").png"; }


if [ -z "$PUUSH_API_KEY" ]; then
  echo "Set the variable PUUSH_API_KEY in $0"
  echo "You can find your API key at http://puush.me/account/settings"

  notify-send -i "$( cd "$( dirname "$0" )" && pwd )/icon.png" "Set the variable PUUSH_API_KEY in $0" "You can find your API key at http://puush.me/account/settings"

  exit 1

elif [ -z "$1" ]; then
	echo "No file entered."
	helpText
  exit 1

fi

#Get file to puush and puush it
case "$1" in
	-d)
		echo "Whole Desktop"
			fileName=$(generateFileName)
			shutter -f -e -n -o "$fileName"
			sleep 3 && puushFile "$fileName"
		;;

	-r)
		echo "Area"
			fileName=$(generateFileName)
			shutter -s -e -n -o "$fileName"
			sleep 3 && puushFile "$fileName"
		;;

	-w)
		echo "Window"
			fileName=$(generateFileName)
			shutter -a -e -n -o "$fileName"
			sleep 3 && puushFile "$fileName"
		;;

	-f)
		echo "File Upload"
			fileName=`zenity --file-selection`
			puushFile "$fileName"
		;;

	-e)
		echo "Clipboard Upload"
			targets=`xclip -selection clipboard -t TARGETS -o`
			fileName="/tmp/puush-linux-clip"

			for target in $targets
			do
				if [[ "$target" =~ "/" ]]; then
					xclip -selection "clipboard" -t "$target" -o > "$fileName"
					puushFile "$fileName"
					exit $?
				fi
			done

			# we're here because clipboard content's MIME-type is not really known. Does it even have a type?
			# well, let's hope for the best and push it as plaintext

			xclip -selection "clipboard" -t "text/plain" -o > "$fileName"
			puushFile "$fileName"
		;;

	-h|--help)
		helpText
		exit 0
		;;
		
	*)
		echo "Upload $1"
			puushFile "$1"
		;;
		
esac
